Update run-unit-tests.yaml

diff --git a/.github/workflows/run-unit-tests.yaml b/.github/workflows/run-unit-tests.yaml
--- a/.github/workflows/run-unit-tests.yaml
+++ b/.github/workflows/run-unit-tests.yaml
@@ -3,40 +3,44 @@ name: Java CI
 on: [push]
 
 permissions:
-  contents: read
+    contents: read
+    checks: write
+    id-token: write
 
 jobs:
   build:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
+    runs-on: macos-latest
 
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up JDK 17
+      - name: Set up JDK
         uses: actions/setup-java@v3
         with:
-          java-version: '17'
           distribution: 'temurin'
+          java-version: '17'
 
-      - name: Test
-        uses: gradle/gradle-build-action@v2
-        with:
-          arguments: test
+      - name: Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@v1
 
-      - name: Build
+      - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
-        with:
-          arguments: build
 
-      - name: Build (jlink)
-        uses: gradle/gradle-build-action@v2
-        with:
-          arguments: jlink
+      - name: Change wrapper permissions
+        run: chmod +x ./gradlew
 
-      - name: Build (jpackage)
-        uses: gradle/gradle-build-action@v2
+      - name: Clean build
+        run: ./gradlew clean
+
+      # build everything (includes running unit tests)
+      - name: Execute Gradle build
+        run: ./gradlew build
+
+      # report the results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          arguments: jpackage
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          detailed_summary: true # display detailed summary of the report
+          include_passed: true # include passed tests in the results table
